<?php 

require_once('conf.php');
require_once('query.php');

/* Create Handler */

if(isset($_SESSION['username'])){
	$submit = $_POST['submit']; //Form Submit Boolean (1 or 0)

	if ($submit == '1'){ //Create Form Submission

		//Get POST stuff and trim whitespace
		$name = trim($_POST['cre_name']);
		$date = trim($_POST['cre_date']);
		$info = trim($_POST['cre_info']);
		
		$subjects = trim($_POST['cre_sele']);
		
		if(strlen(trim($subjects)) > 0){//Check if stuff is actually in the subjects field
			$subjects = explode("\n", $subjects);
			
			foreach ($subjects as $key => $value){
				$subjects[$key] = trim($subjects[$key]);
				
				if ($key > 49){//Max of 50 subjects
					break;
				}
				
				if (strlen($subjects[$key]) > 50){
					$subjects[$key] = substr($subjects[$key], 0, 50);
				}
			}
		}
		
		else{
			$subjects = array();
		}
		
		if (strlen($date) > 0){
			$pDate = date_parse_from_format('Y-m-d H:i:s', $date);//Parsed Date
		}
		
		else{
			$date = '0000-00-00 00:00:00';
		}
			
		if (strlen($name) <= 0 or strlen($name) > 200 or strlen($info) > 1000 or (isset($pDate['errors']) and $pDate['error_count'] + $pDate['warning_count'] > 0)){//Entry Validation ($pDate checks $date)
			?>
			<div class="message error-message" onclick="go_create();">
				<p><strong>One or more of your fields was improperly entered. (Click to try again.)</strong></p>
			</div>
			<?
		}
		
		else{
			$columns = array('title');
			$values = array("'" . sanitize($name) . "'");
			if (getNumOf('psets', $columns, $values) > 0){//Check For Duplicates
				?>
				<div class="message error-message" onclick="go_create();">
					<p><strong>There already exists a set with the exact same name. (Click to try again.)</strong></p>
				</div>
				<?
			}
			
			else{
				$userSelect = selectFrom('users', array('id'), array('username'), array("'" . $_SESSION['username'] . "'"));
				$userID = $userSelect[0]['id'];//Get ID of submitting user
				
				//Random Passwords
				$adminPass = strval(mt_rand(100000,999999));
				$managerPass = strval(mt_rand(100000,999999));
				$editorPass = strval(mt_rand(100000,999999));
				
				$columns = array('title', 'info', 'director_users_id', 'admin_access_code', 'manager_access_code', 'editor_access_code', 'created', 'target');
				$values = array("'" . sanitize($name) . "'", "'" . sanitize($info) . "'", "'" . sanitize($userID) . "'", "'" . sanitize(strval($adminPass)) . "'", "'" . sanitize(strval($managerPass)) . "'", "'" . sanitize(strval($editorPass)) . "'", "NOW()", "'" . sanitize($date) . "'");
				insertInto('psets', $columns, $values);//Insert tournament into database
			
				$setID = strval(mysql_insert_id());//Get (tournament) ID generated by last query
				$columns = array('users_id', 'psets_id', 'role');
				$values = array("'" . sanitize($userID) . "'", "'" . sanitize($setID) . "'", "'d'");
				insertInto('permissions', $columns, $values);//Give creator Director level perms
				
				$columns = array('psets_id', 'subject');
				
				foreach ($subjects as $subject){
					$values = array("'" . sanitize($setID) . "'", "'" . sanitize($subject) . "'");
					insertInto('psets_allocations', $columns, $values);
				}
				
				?>
				<div class="message thank-message">
					<p><strong>Thank you for your submission. You may now use your set.</strong></p>
				</div>
				<?
			}
		}
	}

	else{//General Link
		echo $conf['create'];
		?>
		<p><div id="createform" style="text-align:center;"><div class="box">
			<form id="create" class="postform" onsubmit="submit_create(document.getElementById('create')); return false;">
				<label>Tournament or Set Name: <input type="text" id="cre_name" name="cre_name"></label><br><br>
				<label>Tournament Target Date: <input type="text" id="cre_date" name="cre_date"></label><br><br>
				<label><span class="halfleft">Tournament Information:&nbsp;&nbsp;</span><span class="halfright">Subject Selection:</span><br>
				<textarea type="text" id="cre_info" name="cre_info"></textarea>&nbsp;&nbsp;
				<textarea type="text" id="cre_sele" name="cre_sele"></textarea></label><br><br>
				<input type="submit" value="Create">
			</form>
		</div></div></p>			
		<script type="text/javascript">
			fancy_date('cre_date');
		</script>
		<?
	}
}

else{
	echo $conf['unauthorized'];
}

?>